---
config:
    url         : https://groups.pm.org/groups/losangeles/
    machine     : groups.pm.org
    username    : spazm
    certificate : cacert.pem
location:
  ticketmaster:
    address  : TicketMaster - 7060 Hollywood Blvd, Los Angeles 90028
    mapurl:  http://maps.google.com/maps?f=q&hl=en&q=7060+Hollywood+Blvd,Los+Angeles,+CA+90028
    name     : TicketMaster / Live Nation
    url      : http://ticketmaster.com
  rubicon:
    address : The Rubicon Project HQ - 1925 S. Bundy, Los Angeles, CA, 90025
    mapurl  : ""
    name    : The Rubicon Project
    url     : http://rubiconproject.com
  mt:
    address : Media Temple, 8520 National, Culver City, CA 90232.
    mapurl  : ""
    name    : Media Temple
    url     : http://mediatemple.com
  demand:
    address : Demand Media, 1299 Ocean, Santa Monica, CA
    mapurl  :
    name    : Demand Media
    url     : http://demandmedia.com
  weaver:
    address: ""
    mapurl:  ""
    name:    Language Weaver
    url:     http://languageweaver.com
  oversee:
    address: Oversee - 515 S. Flower Street, Suite 4400, Los Angeles, CA 90071
    mapurl:  http://maps.google.com/maps?f=q&hl=en&q=515+S.+Flower+Street+Los+Angeles,+CA+90071
    name:    Oversee
    url:     http://oversee.net
  rent:
    address: Rent.com - 2425 Olympic Blvd Suite 400 E, Santa Monica, CA 90404
    mapurl:  http://maps.google.com/maps?f=q&hl=en&q=2425+Olympic+Blvd+Ste+400+E+Santa+Monica+90404
    name:    Rent.com
    url:     http://rent.com
  open42:
    address: Open42 - 840 Apollo St.  Suite 223, El Segundo, CA
    mapurl:
    name:    Open42
    url:     http://open42.com
  scale:
    address: Scale10x - Hilton Los Angeles Airport - 5711 West Century Boulevard, 90045
    mapurl: http://maps.google.com/maps?q=5711+West+Century+Boulevard,+Los+Angeles,+California,+USA+90045&hnear=5711+W+Century+Blvd,+Los+Angeles,+California+90045&gl=us&t=m&z=16&vpsrc=0
    url:    https://www.socallinuxexpo.org/scale10x/events/bird-feather-sessions

meetings:
  - event_date: "2012/05/23"
    #ds_std:     TBD: Third or Fourth, Wednesday or Thursday, May 2012
    location:   demand
    open_call:  1
    presentations:
      - presenter : you
        title     : TBD
        abstract  : Informal discussion of tools, comings and goings, etc.
      - presenter : btilly
        title     : Template::ExpandHash (likely postponed)
        abstract  : A new perl module to expand a hash as a template.
        links     :
          - name  : Template::ExpandHash
            url   : https://metacpan.org/module/Template::ExpandHash
          - name  : git
            url   : https://github.com/btilly/Template-ExpandHash
#       - presenter : merlyn
#         title     : Testing Classes with Test::Trap (unconfirmed)
  - event_date: "2012/03/21"
    location: demand
    open_call: 0
    presentations:
      - presenter : thaljef
        title    : Pinto for managing Perl dependencies
        abstract: The CPAN is a blessing and a curse.  You can find code for every problem imaginable, but managing all those dependencies is extremely frustrating.  Until now.  Pinto is one example of a new breed of tools for managing your Perl dependencies.  In this presentation we will explore what Pinto does, demonstrate how to use it in the development cycle, and compare it with similar tools.
      - presenter : tonyg
        title    : Perl for Home Security
        abstract : Tony will share a home security system that he designed that runs on Perl.  His system uses motion sensors, loud sirens, audio announcers, a wireless remote, text message alerts and logs all activity to disk.
        links    :
            - name : ppt
              url  : "http://www.metracom.com/Perl_Alarm.pptx"
  - event_date: "2012/02/23"
    location: demand
    open_call: 1
    presentations:
      - presenter : briandfoy
        title    : How to deliver a presentation
      - presenter : briandfoy
        title    : Zero to Perl, teaching newbies.
        abstract : Introduction to perl for newbies (YAPC.na preview)
  - event_date: "2012/01/21"
    location: scale
    open_call: 1
    presentations:
      - presenter: you
        title: Scale BoF discussion
    cancelled:
      - presenter: spazm
        title    : App::Sulla a jabber bot using Bot::Backbone
        abstract : Example of a xmpp/jabber bot with HTTPD/rest input, using AnyEvent::XMPP and AnyEvent::HTTPD on the backend.
        links:
          - name : src
            url  : http://github.com/spazm/p5-app-sulla
  - event_date: "2011/12/7"
    location: demand
    open_call: 1
    show_news: 0
    presentations:
      - presenter: mike_frager
        title: VOIP with perl and asterisk/freepbx
        links:
          - name: pdf
            url : /presentations/voip/VOIP_with_Perl.pdf
      - presenter: davido
        title: Inline::C, The Eminently Palatable Approach to XS
        abstract: "We will discuss installation, basic use, applications of use such as time optimization, memory optimization, unit testing of C code, linking in specialty C libraries, callbacks, and more.  I'll include a brief discussion on Inline::CPP, which I took over co-maintainership on just a few days ago."
        links:
          - name: Inline::CPP
            url : http://metacpan.org/module/Inline::CPP
          - name: (slides repo)
            url : https://github.com/daoswald/Inline-C-Perl-Mongers-Talk
          - name: slides.odp
            url : https://github.com/daoswald/Inline-C-Perl-Mongers-Talk/blob/master/inline_c_slides.odp
          - name: primes.cpp
            url: "https://github.com/daoswald/Inline-C-Perl-Mongers-Talk/blob/master/primes.cpp"
          - name: primesbench.pl
            url : https://github.com/daoswald/Inline-C-Perl-Mongers-Talk/blob/master/primesbench.pl
  - event_date: "Wednesday October 26, 2011"
    event_date_pretty: Wednesday the 26st
    location: demand
    open_call: 1
    show_news: 1
    presentations:
      - presenter: spazm
        title: use Japan;
        abstract: Some awesome cpan modules from japan, inspired by a YAPC::na lightening talk
        links:
          - name : slides
            url  : http://www.slideshare.net/lestrrat/cpan-gems-from-the-far-east
      - presenter: bluefeet
        title: DBI/SQL stack
        abstract: presenting a DBI/SQL stack that he has been constructing for about a year now.  The talk will cover the whats and hows of SQL::Dialect, SQL::Abstract::Query, and DBIx::ResultSet.  Also to be discussed is DBIx::Lookup and DBIx::AutoID, which are currently in the works.
        links:
          - name : slides
            url  : 

          - name : SQL::Dialect
            url  : http://metacpan.org/module/SQL::Dialect
          - name : (git)
            url  : http://github.com/bluefeet/SQL-Dialect

          - name : SQL::Abstract::Query
            url  : http://metacpan.org/module/SQL::Abstract::Query
          - name : (git)
            url  : http://github.com/bluefeet/SQL-Abstract-Query

          - name : DBIx::ResultSet
            url  : http://metacpan.org/module/DBIx::ResultSet
          - name : (git)
            url  : http://github.com/bluefeet/DBIx-ResultSet

          - name : (DBIx::AutoID git)
            url  : http://github.com/bluefeet/DBIx-AutoID

  - event_date: "Wednesday September 21, 2011"
    event_date_pretty: Wednesday the 21st
    location: mt
    open_call: 1
    show_news: 1
    presentations:
      - presenter: nate_jones
        title: Managing your dotfiles with perl and git
        abstract: "The Managing your dotfiles with perl and git to end all presentations about managing your dotfiles with perl and git"
        links:
          - name : Presentatation
            url  : https://github.com/justone/dfm_present
          - name : ( pdf )
            url  : https://github.com/downloads/justone/dfm_present/dfm_present.pdf
          - name : (main repo)
            url  : https://github.com/justone/dotfiles
      - presenter: mike_frager
        title: Vertical Tables
  - event_date: "Wednesday August 31, 2011"
    event_date_pretty: Wednesday the 31st
    location: ticketmaster
    open_call: 0
    show_news: 1
    presentations: 
      - presenter: plotkin
        title: Implementation of a Custom Facebook Integration
      - presenter: mwolson
        title: Implementation of a Custom Facebook Integration
        links:
          - name : slides
            url  : http://mwolson.org/notes/manual/FacebookSlides.pdf
  - event_date: "Wednesday July 20, 2011"
    event_date_pretty: Some Wednesday in July
    location:
    open_call: 1
    show_news: 1
    presentations:
      - presenter: merlyn
        title: emergency social meeting
  - event_date: "Wednesday May 25, 2011"
    event_date_pretty: Wednesday the 25th
    location: rent
    open_call: 0
    show_news: 1
    presentations:
      - presenter: buddy
        title: Method::Signatures (or, How I Learned to Stop Worrying and Love MooseX::Declare).
        abstract: "MooseX::Declare has a bad rep among most Moose fans, but it turns out that there's nothing wrong with it once you get MooseX::Method::Signatures out of the way.  This is the story of my quest to replace MooseX::Method::Signatures with something based on Method::Signatures, thus improving the reliability, performance, and error reporting of MooseX::Declare."
        obstruct: "Thanx everyone for the encouragement!  I'll be putting the finishing touches on the presentation this weekend, so I should be well and ready by then.  (And if I'm not, then I reckon I'll just be unwell and unready. <g>)  See you guys then!"
        links:
            - name: Method::Signatures
              url:  http://metacpan.org/module/Method::Signatures
            - name: Method::Signatures::Modifiers
              url:  http://metacpan.org/module/Method::Signatures::Modifiers
            - name: first bug
              url:  https://github.com/schwern/method-signatures/issues/36
      - presenter: spazm
        title: "Dancing on Air (or, What's Plack got to do with it?)"
        abstract: "Dancer is a micro web application framework.  <br>PSGI is an interface between web applications and web servers.  <br>Plack is an implementation of PSGI.  <br><br>Put them all together and what do we get?"
  - event_date: "Wednesday April 27, 2011"
    event_date_pretty: Wednesday the 27th
    location: open42
    open_call: 0
    show_news: 1
    presentations:
      - presenter: thaljef
        title: Perl::Critic
        abstract: "Perl::Critic is the leading static analyzer for Perl.  Software development teams (large and small) use Perl::Critic every day to automatically find bugs, manage complexity, and enforce consistency in their Perl source code.  My presentation will demonstrate how to use, configure, and extend Perl::Critic.  I'll also show how to automate and integrate Perl::Critic into your development cycle.  Perl::Critic is available on CPAN here: http://search.cpan.org/dist/Perl-Critic"
        links:
          - name: Perl::Critic
            url:  http://metacpan.com/module/Perl::Critic
      - presenter: beppu
        title: "TBD: Rhetoric: a simple blogging system for perl"
        abstract: "How Beppu got his <del>groove</del>blog back"
  - event_date: "Wednesday, March 23, 2011"
    location: rent
    open_call: 0
    show_news: 1
    event_date_pretty: Wednesday the 23rd
    presentations:
      - presenter: tstanton
        title: Scale9x discussion/review/take-away
      - presenter: bluefeet
        title: TBD: Moose Best Practices
      - presenter: spazm
        title: workflows with Class::Workflow
  - event_date: 'Wednesday, January 19, 2011'
    location: rent
    open_call: 1
    show_news: 1
    event_date_pretty: Wednesday the 19th
    presentations:
      - presenter: rick
        title: Inversion of Control and Dependency Injection, using Bread::Board
      - presenter: tstanton
        title: Blogging in perl -- Anger Whale and Galuga
        abstract: What are the pure-perl blog options available to the hacker who wants to create a blog from text files on a filesystem.
        links:
            - name: slides
              url:  http://tommystanton.com/presentations/20110119-Perl_powered_blogging_software_Angerwhale_to_Galuga/ 
            - name: tarball
              url:  http://tommystanton.com/presentations/20110119-Perl_powered_blogging_software_Angerwhale_to_Galuga.tar.gz
  - event_date: 'Thursday, July 16, 2009'
    event_date_pretty: Thursday the 16th
    presentations:
      - presenter: xantus
        title: "Mojo and <href='http://mojolicious.org'>mojolicious</a> -- A next generation web framework for the Perl programming language.  Presentation and examples."
      - presenter: mcl
        title: 'Interviewing Perl Programmers -- How to find the best: what to look for, what to ask, what to say: A Q&A'
  - event_date: 'Thursday, August 27, 2009'
    event_date_pretty: Thursday the 27th
    open_call: 1
    presentations:
      - presenter: kenny
        title: unknown presentation. canceled by busy work schedule.
      - presenter: you
        title: talking about stuff
  - event_date: 'Wednesday, June 30, 2010'
    event_date_pretty: Wednesday the 30th
    open_call: 1
    presentations: []
  - event_date: 'Wednesday, July 28, 2010'
    event_date_pretty: Wednesday the 28th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: pe-cpp produces "sliced" c-pre-processor header files and does partial evaluation of arithmetic expressions to create simplified sources via source-to-source transforms.
        presenter: guyshaw
        title: pe-cpp, a partial c-pre-processor evaluator
      - abstract: Graphics and data filtering techniques in Perl toward losing weight considered as an engineering problem.
        presenter: troywill
        title: Losing weight with perl
  - event_date: 'Wednesday, August 25, 2010'
    event_date_pretty: Wednesday the 25th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: App::Cmd is an awesome module for making extendable comandline applications.
        presenter: spazm
        title: Getting started with App::Cmd
      - abstract: ""
        presenter: bluefeet
        title: 12 CPAN Distros in 12 penta-Minutes
  - event_date: 'Wednesday, Sept 22, 2010'
    event_date_pretty: Wednesday the 22th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: "A program provided by this distribution, \"git-home-sync\", is used to automate  the git/system commands necessary to get a user's home directory to be synced with a Git repository. This allows the user to track things like dot files, making them available on a brand new machine.  For example, your ~/.vimrc and/or ~/.emacs will always be the same on all machines that you use."
        presenter: tstanton
        title: "App::Git::HomeSync: A CPAN module almost finished"
      - abstract: ""
        presenter: bluefeet
        title: 12 CPAN Distros in 12 penta-Minutes
        presenter:
  - event_date: Wednesday, October 13, 2010
    location: oversee
    event_date_pretty: Wednesday the 13th
    open_call: 1
    show_news: 1
    presentations:
      - presenter: you
        title: TBD
      - presenter: merlyn
        title: TBD
        abstract: A lightning talk? One of his hour long presentations?  Q&A with Randal?  Crazy technical interview questions: you ask them, he answers them and then critiques them.
  - event_date: Wednesday, November 17, 2010
    location: mt
    event_date_pretty: Wednesday the 17th
    open_call: 1
    show_news: 1
    presentations:
      - presenter: jbarratt
        title: AnyEvent -- Perl Asynchronous Programming
        abstract: Event driven programming has been a powerful paradigm for years, but it's emerging as an increasingly important way to work. Making events easy is part of what has made node.js so exciting, and is possible in Python with Eventlet and Ruby with EventMachine. Perl's answer to this is very mature and flexible: AnyEvent. As well as an introduction to the module, how to use it, and some of the other modules in the "family", we'll cover some before/after examples of synchronous code made asynchronous.
      - presenter: gabec
        title: Epistemology & Perl Oracles
        abstract: Most of us are familiar with the output of Perl's native test oracle every time we install a module from CPAN, ok, not ok.  When testing, did you ever think that you might need to know more than that to isolate faults?  This discussion covers the Test Anything Protocol (TAP), capturing system events & using Perl to lean more what you know & what you don't know about the application you are testing.
presenter:
  gabec:
    name: Gabe Costello
    description: is a Software Quality Assurance Engineer at MediaTemple.
  jbarratt:
    name: Josh Barratt
    description: is CTO of MediaTemple.
    github: jbarratt
  guyshaw:
    name: Guy Shaw
  briandfoy:
    name: brian d foy
    cpan: bdfoy
    github: briandfoy
    url: http://www252.pair.com/~comdog/
  buddy:
    name: Buddy Burden
    description: is Just another barefoot coder at Rent.com
    cpan:     barefoot
    facebook: barefootcoder
    github:   barefootcoder
    url: 
  bluefeet:
    cpan: bluefeet
    github: bluefeet
    description: 'ran the Thousand-oaks perl mongers, contributes to CPAN and now writes code for rent.com'
    name: Aran Deltac
    url: http://bluefeet.net
  kenny:
    description: 'works at ValueClick, creating a new monitoring ubersystem.  In his spare time he has a number of ventures to help lift others up by their bootstraps. '
    name: Kenny Flegal
  mcl:
    description: is a software engineer and team lead at the Rubicon project.
    name: Mon-Chaio Lo
  spazm:
    cpan: spazm
    description: runs the Los Angeles Perl Mongers and serves as <strike>Chief Ninjaneer for [undisclosed startup]</strike>Lead Engineer at Demand Media.
    name: Andrew Grangaard
    github: spazm
    url: http://lowlevelmanager.com
  troywill:
    description: is Just a geek who loves Perl
    github: troywill
    name: Troy Will
    url: http://troywill.com
  tstanton:
    cpan: tstanton
    description: "Tommy's interests are: 1) Tappin' on the command-line, in a GNU/Linux setting; 2) Pickin' on the banjo, in a bluegrass setting"
    #github: tstanton
    name: Tommy Stanton
    url: http://tommystanton.com
  xantus:
    name:
    cpan: xantus
    description: is a software engineer who specializes in rich front-end applications and scalable back-end servers.
    url: http://xant.us
  merlyn:
    name: Randal Schwartz
    cpan: merlyn
    github: RandalSchwartz
    url: http://merlyn.posterous.com/
    description: -- Just another perl hacker
  rick:
    name: Rick Apichairuk
  thaljef:
    name: Jeffrey Thalhammer
    description: The Perl Critic!
    cpan: thaljef
    github: thaljef
    url: http://perlcritic.org/
  beppu:
    name: John Beppu
    description:
    cpan: beppu
    github: beppu
  plotkin:
    name: Jacob Plotkin
    linkedin: http://www.linkedin.com/pub/jacob-plotkin/2/742/939
    description: ticketmaster engineer
  mwolson:
    name: Michael Olson
    description: ticketmaster engineer
    url: http://mwolson.org/
  nate_jones:
    name: Nate Jones
  a_ticketmaster_engineer:
    description: To be named later.
    name: A ticketmaster engineer
  mike_frager:
    name: Mike Frager
  davido:
    name: David Oswald
    cpan: davido
    github: daoswald
  tonyg:
    name: Tony Gasparovic
  btilly:
    name: Ben Tilly
    cpan: tilly
    github: btilly
  you:
    description: are an awesome perler!
    name: You
    url: http://127.0.0.1
