---
config:
    url         : https://groups.pm.org/groups/losangeles/
    machine     : groups.pm.org
    username    : spazm
    certificate : cacert.pem
location:
  ticketmaster:
    address  : TicketMaster - 7060 Hollywood Blvd, Los Angeles 90028
    mapurl:  http://maps.google.com/maps?f=q&hl=en&q=7060+Hollywood+Blvd,Los+Angeles,+CA+90028
    name     : TicketMaster / Live Nation
    url      : http://ticketmaster.com
  rubicon:
    address : The Rubicon Project HQ - 1925 S. Bundy, Los Angeles, CA, 90025
    mapurl  : ""
    name    : The Rubicon Project
    url     : http://rubiconproject.com
  mt:
    address : Media Temple, 8520 National, Culver City, CA 90232.
    mapurl  : ""
    name    : Media Temple
    url     : http://mediatemple.com
  demand:
    address : Demand Media, 1299 Ocean, Santa Monica, CA
    mapurl  :
    name    : Demand Media
    url     : http://demandmedia.com
  weaver:
    address: ""
    mapurl:  ""
    name:    Language Weaver
    url:     http://languageweaver.com
  oversee:
    address: Oversee - 515 S. Flower Street, Suite 4400, Los Angeles, CA 90071
    mapurl:  http://maps.google.com/maps?f=q&hl=en&q=515+S.+Flower+Street+Los+Angeles,+CA+90071
    name:    Oversee
    url:     http://oversee.net
  rent:
    address: Rent.com - 2425 Olympic Blvd Suite 400 E, Santa Monica, CA 90404
    mapurl:  http://maps.google.com/maps?f=q&hl=en&q=2425+Olympic+Blvd+Ste+400+E+Santa+Monica+90404
    name:    Rent.com
    url:     http://rent.com
  open42:
    address: Open42 - 840 Apollo St.  Suite 223, El Segundo, CA 
    mapurl:
    name:    Open42
    url:     http://open42.com

meetings:
  - event_date: "Wednesday October 26, 2011"
    event_date_pretty: Wednesday the 26st
    location: demand 
    open_call: 1
    show_news: 1
    presentations:
      - presenter: spazm
        title: use Japan;
        abstract: Some awesome cpan modules from japan, inspired by a YAPC::na lightening talk
      - presenter: bluefeet
        title: DBI/SQL stack
        abstract: presenting a DBI/SQL stack that he has been constructing for about a year now.  The talk will cover the whats and hows of SQL::Dialect, SQL::Abstract::Query, and DBIx::ResultSet.  Also to be discussed is DBIx::Lookup and DBIx::AutoID, which are currently in the works.
  - event_date: "Wednesday September 21, 2011"
    event_date_pretty: Wednesday the 21st
    location: mt
    open_call: 1
    show_news: 1
    presentations:
      - presenter: nate_jones
        title: Managing your dotfiles with perl and git
        abstract: "The Managing your dotfiles with perl and git to end all presentations about managing your dotfiles with perl and git"
      - presenter: you
        title: TBD
  - event_date: "Wednesday August 31, 2011"
    event_date_pretty: Wednesday the 31st
    location: ticketmaster
    open_call: 0
    show_news: 1
    presentations: 
      - presenter: plotkin
        title: Implementation of a Custom Facebook Integration
      - presenter: olson
        title: Implementation of a Custom Facebook Integration
  - event_date: "Wednesday July 20, 2011"
    event_date_pretty: Some Wednesday in July
    location: tbd
    open_call: 1
    show_news: 1
    presentations:
      - presenter: you
        title: awesomeness
        abstract: what have you been up to?

  - event_date: "Wednesday May 25, 2011"
    event_date_pretty: Wednesday the 25th
    location: rent
    open_call: 0
    show_news: 1
    presentations:
      - presenter: buddy
        title: Method::Signatures (or, How I Learned to Stop Worrying and Love MooseX::Declare).
        abstract: "MooseX::Declare has a bad rep among most Moose fans, but it turns out that there's nothing wrong with it once you get MooseX::Method::Signatures out of the way.  This is the story of my quest to replace MooseX::Method::Signatures with something based on Method::Signatures, thus improving the reliability, performance, and error reporting of MooseX::Declare."
        obstruct: "Thanx everyone for the encouragement!  I'll be putting the finishing touches on the presentation this weekend, so I should be well and ready by then.  (And if I'm not, then I reckon I'll just be unwell and unready. <g>)  See you guys then!"
      - presenter: spazm
        title: "Dancing on Air (or, What's Plack got to do with it?)"
        abstract: "Dancer is a micro web application framework.  <br>PSGI is an interface between web applications and web servers.  <br>Plack is an implementation of PSGI.  <br><br>Put them all together and what do we get?"
  - event_date: "Wednesday April 27, 2011"
    event_date_pretty: Wednesday the 27th
    location: open42
    open_call: 0
    show_news: 1
    presentations:
      - presenter: thaljef
        title: Perl::Critic
        abstract: "Perl::Critic is the leading static analyzer for Perl.  Software development teams (large and small) use Perl::Critic every day to automatically find bugs, manage complexity, and enforce consistency in their Perl source code.  My presentation will demonstrate how to use, configure, and extend Perl::Critic.  I'll also show how to automate and integrate Perl::Critic into your development cycle.  Perl::Critic is available on CPAN here: http://search.cpan.org/dist/Perl-Critic"
      - presenter: beppu
        title: "TBD: Rhetoric: a simple blogging system for perl"
        abstract: "How Beppu got his <del>groove</del>blog back"
  - event_date: "Wednesday, March 23, 2011"
    location: rent
    open_call: 0
    show_news: 1
    event_date_pretty: Wednesday the 23rd
    presentations:
      - presenter: tstanton
        title: Scale9x discussion/review/take-away
      - presenter: bluefeet
        title: TBD: Moose Best Practices
      - presenter: spazm
        title: workflows with Class::Workflow
  - event_date: 'Wednesday, January 19, 2011'
    location: rent
    open_call: 1
    show_news: 1
    event_date_pretty: Wednesday the 19th
    presentations:
      - presenter: rick
        title: Inversion of Control and Dependency Injection, using Bread::Board
      - presenter: tstanton
        title: Blogging in perl -- Anger Whale and Galuga
        abstract: What are the pure-perl blog options available to the hacker who wants to createa blog from text files on a filesystem.
  - event_date: 'Thursday, July 16, 2009'
    event_date_pretty: Thursday the 16th
    presentations:
      - presenter: xantus
        title: "Mojo and <href='http://mojolicious.org'>mojolicious</a> -- A next generation web framework for the Perl programming language.  Presentation and examples."
      - presenter: mcl
        title: 'Interviewing Perl Programmers -- How to find the best: what to look for, what to ask, what to say: A Q&A'
  - event_date: 'Thursday, August 27, 2009'
    event_date_pretty: Thursday the 27th
    open_call: 1
    presentations:
      - presenter: kenny
        title: unknown presentation. canceled by busy work schedule.
      - presenter: you
        title: talking about stuff
  - event_date: 'Wednesday, June 30, 2010'
    event_date_pretty: Wednesday the 30th
    open_call: 1
    presentations: []
  - event_date: 'Wednesday, July 28, 2010'
    event_date_pretty: Wednesday the 28th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: pe-cpp produces "sliced" c-pre-processor header files and does partial evaluation of arithmetic expressions to create simplified sources via source-to-source transforms.
        presenter: guyshaw
        title: pe-cpp, a partial c-pre-processor evaluator
      - abstract: Graphics and data filtering techniques in Perl toward losing weight considered as an engineering problem.
        presenter: troywill
        title: Losing weight with perl
  - event_date: 'Wednesday, August 25, 2010'
    event_date_pretty: Wednesday the 25th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: App::Cmd is an awesome module for making extendable comandline applications.
        presenter: spazm
        title: Getting started with App::Cmd
      - abstract: ""
        presenter: bluefeet
        title: 12 CPAN Distros in 12 penta-Minutes
  - event_date: 'Wednesday, Sept 22, 2010'
    event_date_pretty: Wednesday the 22th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: "A program provided by this distribution, \"git-home-sync\", is used to automate  the git/system commands necessary to get a user's home directory to be synced with a Git repository. This allows the user to track things like dot files, making them available on a brand new machine.  For example, your ~/.vimrc and/or ~/.emacs will always be the same on all machines that you use."
        presenter: tstanton
        title: "App::Git::HomeSync: A CPAN module almost finished"
      - abstract: ""
        presenter: bluefeet
        title: 12 CPAN Distros in 12 penta-Minutes
        presenter:
  - event_date: Wednesday, October 13, 2010
    location: oversee
    event_date_pretty: Wednesday the 13th
    open_call: 1
    show_news: 1
    presentations: 
      - presenter: you
        title: TBD
      - presenter: merlyn
        title: TBD
        abstract: A lightning talk? One of his hour long presentations?  Q&A with Randal?  Crazy technical interview questions: you ask them, he answers them and then critiques them.
  - event_date: Wednesday, November 17, 2010
    location: mt
    event_date_pretty: Wednesday the 17th
    open_call: 1
    show_news: 1
    presentations: 
      - presenter: jbarratt
        title: AnyEvent -- Perl Asynchronous Programming
        abstract: Event driven programming has been a powerful paradigm for years, but it's emerging as an increasingly important way to work. Making events easy is part of what has made node.js so exciting, and is possible in Python with Eventlet and Ruby with EventMachine. Perl's answer to this is very mature and flexible: AnyEvent. As well as an introduction to the module, how to use it, and some of the other modules in the "family", we'll cover some before/after examples of synchronous code made asynchronous.
      - presenter: gabec
        title: Epistemology & Perl Oracles
        abstract: Most of us are familiar with the output of Perl's native test oracle every time we install a module from CPAN, ok, not ok.  When testing, did you ever think that you might need to know more than that to isolate faults?  This discussion covers the Test Anything Protocol (TAP), capturing system events & using Perl to lean more what you know & what you don't know about the application you are testing.
  - event_date: 'Wednesday, January 19, 2011'
    location: rent
    open_call: 1
    show_news: 1
    event_date_pretty: Wednesday the 19th
    presentations:
      - presenter: rick
        title: Inversion of Control and Dependency Injection, using Bread::Board
      - presenter: tstanton
        title: Perl-powered blogging software: Angerwhale to Galuga
        abstract: "I've wanted to host my own blog for over a year now, but I'm stubborn and I have refused to use software that isn't: (1) Powered by Perl; (2) In the culture of the CPAN."
        links:
            - name: slides
              url:  http://tommystanton.com/presentations/20110119-Perl_powered_blogging_software_Angerwhale_to_Galuga/ 
            - name: tarball
              url:  http://tommystanton.com/presentations/20110119-Perl_powered_blogging_software_Angerwhale_to_Galuga.tar.gz
presenter:
  gabec:
    name: Gabe Costello
    description: is a Software Quality Assurance Engineer at MediaTemple.
  jbarratt:
    name: Josh Barratt
    description: is CTO of MediaTemple.
    github: jbarratt
  guyshaw:
    name: Guy Shaw
  buddy:
    name: Buddy Burden
    description: is Just another barefoot coder at Rent.com
    cpan:     barefoot
    facebook: barefootcoder
    github:   barefootcoder
    url: 
  bluefeet:
    cpan: bluefeet
    github: bluefeet
    description: 'ran the Thousand-oaks perl mongers, contributes to CPAN and now writes code for rent.com'
    name: Aran Deltac
    url: http://bluefeet.net
  kenny:
    description: 'works at ValueClick, creating a new monitoring ubersystem.  In his spare time he has a number of ventures to help lift others up by their bootstraps. '
    name: Kenny Flegal
  mcl:
    description: is a software engineer and team lead at the Rubicon project.
    name: Mon-Chaio Lo
  spazm:
    cpan: spazm
    description: runs the Los Angeles Perl Mongers and serves as <strike>Chief Ninjaneer for [undisclosed startup]</strike>Lead Engineer at Demand Media.
    name: Andrew Grangaard
    github: spazm
    url: http://lowlevelmanager.com
  troywill:
    description: is Just a geek who loves Perl
    github: troywill
    name: Troy Will
    url: http://troywill.com
  tstanton:
    cpan: tstanton
    description: "Tommy's interests are: 1) Tappin' on the command-line, in a GNU/Linux setting; 2) Pickin' on the banjo, in a bluegrass setting"
    #github: tstanton
    name: Tommy Stanton
    url: http://tommystanton.com
  xantus:
    name: 
    cpan: xantus
    description: is a software engineer who specializes in rich front-end applications and scalable back-end servers.
    url: http://xant.us
  merlyn: 
    name: Randal Schwartz
    cpan: merlyn
    github: RandalSchwartz
    url: http://merlyn.posterous.com/
    description: -- Just another perl hacker
  rick:
    name: Rick Apichairuk
  thaljef:
    name: Jeffrey Thalhammer
    description: The Perl Critic!
    cpan: thaljef
    github: thaljef
    url: http://perlcritic.org/
  beppu:
    name: John Beppu
    description:
    cpan: beppu
    github: beppu
  plotkin:
    name: Jacob Plotkin
    linkedin: http://www.linkedin.com/pub/jacob-plotkin/2/742/939
    description: ticketmaster engineer
  olson:
    name: Michael Olson
    description: ticketmaster engineer
  nate_jones:
    name: Nate Jones
  a_ticketmaster_engineer:
    description: To be named later.
    name: A ticketmaster engineer
  you:
    description: are an awesome perler!
    name: You
    url: http://127.0.0.1
