---
config:
    url      : https://groups.pm.org/groups/losangeles/
    machine  : groups.pm.org
    username : spazm
location:
  rubicon:
    address: The Rubicon Project HQ - 1925 S. Bundy, Los Angeles, CA, 90025
    mapurl:  ""
    name:    The Rubicon Project
    url:     http://rubiconproject.com
  mt:
    address: Media Temple, 8520 National, Culver City, CA 90232.
    mapurl:  ""
    name:    Media Temple
    url:     http://mediatemple.com
  weaver:
    address: ""
    mapurl:  ""
    name:    Language Weaver
    url:     http://languageweaver.com
  oversee:
    address: Oversee - 515 S. Flower Street, Suite 4400, Los Angeles, CA 90071
    mapurl:  http://maps.google.com/maps?f=q&hl=en&q=515+S.+Flower+Street+Los+Angeles,+CA+90071
    name:    Oversee
    url:     http://oversee.net

meetings:
  - event_date: 'Thursday, July 16, 2009'
    event_date_pretty: Thursday the 16th
    presentations:
      - presenter: xantus
        title: "Mojo and <href='http://mojolicious.org'>mojolicious</a> -- A next generation web framework for the Perl programming language.  Presentation and examples."
      - presenter: mcl
        title: 'Interviewing Perl Programmers -- How to find the best: what to look for, what to ask, what to say: A Q&A'
  - event_date: 'Thursday, August 27, 2009'
    event_date_pretty: Thursday the 27th
    open_call: 1
    presentations:
      - presenter: kenny
        title: unknown presentation. canceled by busy work schedule.
      - presenter: you
        title: talking about stuff
  - event_date: 'Wednesday, June 30, 2010'
    event_date_pretty: Wednesday the 30th
    open_call: 1
    presentations: []
  - event_date: 'Wednesday, July 28, 2010'
    event_date_pretty: Wednesday the 28th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: pe-cpp produces "sliced" c-pre-processor header files and does partial evaluation of arithmetic expressions to create simplified sources via source-to-source transforms.
        presenter: guyshaw
        title: pe-cpp, a partial c-pre-processor evaluator
      - abstract: Graphics and data filtering techniques in Perl toward losing weight considered as an engineering problem.
        presenter: troywill
        title: Losing weight with perl
  - event_date: 'Wednesday, August 25, 2010'
    event_date_pretty: Wednesday the 25th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: App::Cmd is an awesome module for making extendable comandline applications.
        presenter: spazm
        title: Getting started with App::Cmd
      - abstract: ""
        presenter: bluefeet
        title: 12 CPAN Distros in 12 penta-Minutes
  - event_date: 'Wednesday, Sept 22, 2010'
    event_date_pretty: Wednesday the 22th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: ""
        presenter: tstanton
        title: App::Git::HomeSync
      - abstract: ""
        presenter: bluefeet
        title: 12 CPAN Distros in 12 penta-Minutes
        presenter:
  - event_date: Wednesday, October 13, 2010
    location: oversee
    event_date_pretty: Wednesday the 13th
    open_call: 1
    show_news: 1
    presentations: 
      - presenter: you
        title: TBD
      - presenter: merlyn
        title: TBD
        abstract: A lightning talk? One of his hour long presentations?  Q&A with Randal?  Crazy technical interview questions: you ask them, he answers them and then critiques them.
  - event_date: Wednesday, November 17, 2010
    location: mt
    event_date_pretty: Wednesday the 17th
    open_call: 1
    show_news: 1
    presentations: 
      - presenter: joshb
        title: AnyEvent -- Perl Asynchronous Programming
        abstract: Event driven programming has been a powerful paradigm for years, but it's emerging as an increasingly important way to work. Making events easy is part of what has made node.js so exciting, and is possible in Python with Eventlet and Ruby with EventMachine. Perl's answer to this is very mature and flexible: AnyEvent. As well as an introduction to the module, how to use it, and some of the other modules in the "family", we'll cover some before/after examples of synchronous code made asynchronous.
      - presenter: gabec
        title: Epistemology & Perl Oracles
        abstract: Most of us are familiar with the output of Perl's native test oracle every time we install a module from CPAN, ok, not ok.  When testing, did you ever think that you might need to know more than that to isolate faults?  This discussion covers the Test Anything Protocol (TAP), capturing system events & using Perl to lean more what you know & what you don't know about the application you are testing.
presenter:
  gabec:
    name: Gabe Costello
    description: is a Software Quality Assurance Engineer at MediaTemple.
  joshb:
    name: Josh Barratt
    description: is CTO of MediaTemple.
  guyshaw:
    name: Guy Shaw
  bluefeet:
    cpan: bluefeet
    github: bluefeet
    description: 'runs the Thousand-oaks perl mongers, contributes to CPAN and runs a major perl initiative for ValueClick.com'
    name: Aran Deltac
    url: http://bluefeet.net
  kenny:
    description: 'works at ValueClick, creating a new monitoring ubersystem.  In his spare time he has a number of ventures to help lift others up by their bootstraps. '
    name: Kenny Flegal
  mcl:
    description: is a software engineer and team lead at the Rubicon project.
    name: Mon-Chaio Lo
  spazm:
    cpan: spazm
    description: ""
    name: Andrew Grangaard
    github: spazm
    url: http://lowlevelmanager.com
  troywill:
    description: is Just a geek who loves Perl
    github: troywill
    name: Troy Will
    url: http://troywill.com
  tstanton:
    cpan: tstanton
    description: ""
    #github: tstanton
    name: Tommy Stanton
    url: http://tommystanton.com
  xantus:
    cpan: xantus
    description: is a software engineer who specializes in rich front-end applications and scalable back-end servers.
    url: http://xant.us
  merlyn: 
    cpan: merlyn
    name: Randal Schwartz
    description: -- Just another perl hacker
    url: http://merlyn.posterous.com/
    github: RandalSchwartz
  you:
    description: are an awesome perler!
    name: You
    url: http://127.0.0.1
