---
config:
    url : https://groups.pm.org/groups/los-angeles/
    user: spazm
location:
  rubicon:
    address: 1925 S. Bundy
    mapurl: ""
    name: The Rubicon Project
    url: http://rubiconproject.com
  weaver:
    address: ""
    mapurl: ""
    name: Language Weaver
    url: http://languageweaver.com
meetings:
  - event_date: 'Thursday, July 16, 2009'
    event_date_pretty: Thursday the 16th
    presentations:
      - presenter: xantus
        title: "Mojo and <href='http://mojolicious.org'>mojolicious</a> -- A next generation web framework for the Perl programming language.  Presentation and examples."
      - presenter: mcl
        title: 'Interviewing Perl Programmers -- How to find the best: what to look for, what to ask, what to say: A Q&A'
  - event_date: 'Thursday, August 27, 2009'
    event_date_pretty: Thursday the 27th
    open_call: 1
    presentations:
      - presenter: kenny
        title: unknown presentation. canceled by busy work schedule.
      - presenter: you
        title: talking about stuff
  - event_date: 'Wednesday, June 30, 2010'
    event_date_pretty: Wednesday the 30th
    open_call: 1
    presentations: []
  - event_date: 'Wednesday, July 28, 2010'
    event_date_pretty: Wednesday the 28th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: pe-cpp produces "sliced" c-pre-processor header files and does partial evaluation of arithmetic expressions to create simplified sources via source-to-source transforms.
        presenter: guyshaw
        title: pe-cpp, a partial c-pre-processor evaluator
      - abstract: Graphics and data filtering techniques in Perl toward losing weight considered as an engineering problem.
        presenter: troywill
        title: Losing weight with perl
  - event_date: 'Wednesday, August 25, 2010'
    event_date_pretty: Wednesday the 25th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: App::Cmd is an awesome module for making extendable comandline applications.
        presenter: spazm
        title: Getting started with App::Cmd
      - abstract: ""
        presenter: bluefeet
        title: 12 CPAN Distros in 12 penta-Minutes
  - event_date: 'Wednesday, Sept 22, 2010'
    event_date_pretty: Wednesday the 22th
    open_call: 0
    show_news: 1
    presentations:
      - abstract: ""
        presenter: tstanton
        title: App::Git::HomeSync
      - abstract: ""
        presenter: bluefeet
        title: 12 CPAN Distros in 12 penta-Minutes
        presenter:
presenter:
  guyshaw:
    name: Guy Shaw
  bluefeet:
    cpan: bluefeet
    github: bluefeet
    description: 'runs the Thousand-oaks perl mongers, contributes to CPAN and runs a major perl initiative for ValueClick.com'
    name: Aran Deltac
    url: http://bluefeet.net
  kenny:
    description: 'works at ValueClick, creating a new monitoring ubersystem.  In his spare time he has a number of ventures to help lift others up by their bootstraps. '
    name: Kenny Flegal
  mcl:
    description: is a software engineer and team lead at the Rubicon project.
    name: Mon-Chaio Lo
  spazm:
    cpan: spazm
    description: ""
    name: Andrew Grangaard
    github: spazm
    url: http://lowlevelmanager.com
  troywill:
    description: Just a geek who loves Perl
    github: troywill
    name: Troy Will
    url: http://troywill.com
  tstanton:
    cpan: tstanton
    description: ""
    ;github: tstanton
    name: Tommy Stanton
    url: http://tommystanton.com
  xantus:
    cpan: xantus
    description: is a software engineer who specializes in rich front-end applications and scalable back-end servers.
    url: http://xant.us
  merlyn: 
    cpan: merlyn
    description: 
    url: 
    github: RandalSchwartz

  you:
    description: are an awesome perler!
    name: You
    url: http://127.0.0.1
